name: Build/Test

on:
- push
- pull_request

jobs:
  build:
    name: .NET on ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        configuration:
        - debug
        - release

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2

    - name: Build Solution
      run: dotnet build -c ${{ matrix.configuration }} src/shamir.sln
