name: Build/Test

on:
- push
- pull_request

jobs:
  build:
    name: ${{matrix.configuration}} - .NET on ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu
        - macos
        - windows
        configuration:
        - Debug
        - Release
        sdk:
        - 5.0.x

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: ${{ matrix.sdk }}

    - name: Build Solution
      run: dotnet build -c ${{ matrix.configuration }} shamir.sln

    - name: Run Tests
      run: dotnet test -c ${{ matrix.configuration }} shamir.sln
